version: '3.7'
services:
   mysql:
     image: mysql:8.0
     ports:
       - '3307:3306'
     environment:
       - MYSQL_RANDOM_ROOT_PASSWORD=yes
       - MYSQL_DATABASE=app
       - MYSQL_USER=app
       - MYSQL_PASSWORD=pass
   postgres:
     image: postgres:13-alpine
     ports:
       - '5433:5432'
     environment:
       - POSTGRES_USER=app
       - POSTGRES_DB=app
       - POSTGRES_PASSWORD=pass
   node-service:
     build: gate-simulator
     image: node-service.1.0
     ports:
       - '9999:9999'
